version: "3.3"
services:
  school_service:
    build: .
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: school
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root